{"edited":false,"parent_id":"t1_cu3g1","id":"cu3lw","author_flair_text":null,"author":"YAD","distinguished":null,"retrieved_on":1473808070,"gilded":0,"subreddit_id":"t5_2fwo","stickied":false,"link_id":"t3_u1h2","controversiality":0,"body":"Yes, you have to check for something like \"Success return_val\" vs. \"Failure\".  This works well for nonfatal problems where the calling function can move on to the next item or step.","score":2,"ups":2,"created_utc":1165577745,"author_flair_css_class":null,"subreddit":"programming","timestamp_epoch":1566236763,"message_id":"15774-fe406644-5bcc-4595-b138-bbbe145f2724-1566236763"}