{"author":"ntoshev","author_flair_text":null,"parent_id":"t1_cuwqc","edited":false,"id":"cuws2","gilded":0,"retrieved_on":1473808619,"distinguished":null,"body":"You should wrap that in another try-catch to make comparison fair with the version that does not propagate exceptions up. In this method or in a caller, you *need* to write it, because it is a checked exception.","controversiality":0,"link_id":"t3_utqb","stickied":false,"subreddit_id":"t5_2fwo","subreddit":"programming","author_flair_css_class":null,"created_utc":1166194785,"ups":2,"score":2,"timestamp_epoch":1566236769,"message_id":"30507-de40f7f1-9999-4e7c-808e-1621d51f352b-1566236769"}