{"body":"I'm running Python2.4 on Win32 under cygwin.\r\n\r\nJust installed ctypes and docutils.\r\n\r\nI get the following:\r\n\r\nTraceback (most recent call last):\r\n  File \"tests/test.py\", line 206, in ?\r\n    import tests.regression\r\n  File \"/cygdrive/c/src/pyglet/tests/regression/__init__.py\", line 11, in ?\r\n    from pyglet.image import BufferImage\r\n  File \"/cygdrive/c/src/pyglet/pyglet/image/__init__.py\", line 15, in ?\r\n    from pyglet.GL.info import have_extension\r\n  File \"/cygdrive/c/src/pyglet/pyglet/GL/__init__.py\", line 79, in ?\r\n    raise ImportError('GL shared library not found')\r\nImportError: GL shared library not found\r\n","controversiality":0,"subreddit_id":"t5_2fwo","stickied":false,"link_id":"t3_vhr9","subreddit":"programming","ups":1,"score":1,"created_utc":1166644544,"author_flair_css_class":null,"author":"lex99","author_flair_text":null,"parent_id":"t3_vhr9","edited":false,"id":"cvjb3","gilded":0,"distinguished":null,"retrieved_on":1473809048,"timestamp_epoch":1566236773,"message_id":"41614-fb655dc0-5f9d-47ee-bb7d-4290e40eb1ef-1566236773"}