{"gilded":0,"retrieved_on":1473809205,"distinguished":null,"author":"OMouse","author_flair_text":null,"id":"cvrfj","edited":false,"parent_id":"t1_cvrd8","subreddit":"programming","author_flair_css_class":null,"created_utc":1166807562,"score":2,"ups":2,"controversiality":0,"body":"It's strange that Python will just accept it. I thought they applied the \"if there's an error crash spectacularly\" idea.","link_id":"t3_vr55","stickied":false,"subreddit_id":"t5_2fwo","timestamp_epoch":1566236775,"message_id":"45696-1b7a794d-8d83-47ce-b2e0-43678d3c5371-1566236775"}